### ISSUE TITLE
Current Cell Line 03-createDrugFile.R (which calls mapDrugsToPubchem.R) hits the Github timeout error (6 hours)

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#100]
This issue has overlap with #99. Both may be solved by the same thing.

Individual GitHub jobs can only run for 6 hours. This script currently hits this limit and [cancels](https://github.com/PNNL-CompBio/coderdata/actions/runs/7859418845/job/21496478073#step:11:3179).

Conversion to Python is underway soon and this may solve the issue. I'll attempt to multithread this process and that should reduce time substantially.

If this doesn't work, the script may have to be split up to run across multiple jobs.

**Comment by sgosline** [comment]
I'm guessing python with threads will work. Keep me posted.

**Comment by jjacobson95** [comment]
Multiple threads did not work. API limit is pretty slow so this is just a long step. I've split this across multiple jobs and each is limited to 5 hours (so it doesn't trigger a github kill switch). Still working out exactly how many jobs are needed.

Currently, identical docker containers are built in each job. This works but adds a lot of time. To speed this up we might want to consider pushing to dockerhub at the start and then pulling for each job.

**Comment by sgosline** [comment]
that's an easy change- building and pushing to dockerhub should be straightforward, i have example YAML files if you need.

**Comment by jjacobson95** [comment]
Lets track progress for dockerhub in #88.

**Comment by jjacobson95** [comment]
Just a note - two methods to improve performance are in progress. This will use dockerhub as well as a secondary optional file with a list of chem name that should not be re-run (each time this runs, it starts from the beginning and reruns those that previously failed).

**Comment by jjacobson95** [comment]
Commit [78c3786](https://github.com/PNNL-CompBio/coderdata/commit/78c3786abe940e442db64f960e3df0da7500e211) adds an ignore file so certain drugs will not be looked up multiple times. This should improve drug look up speed in the pipeline substantially.

**Comment by jjacobson95** [comment]
Commit [70c02c6](https://github.com/PNNL-CompBio/coderdata/commit/70c02c6a8baaeb90b82f0288a5350a2974910626) adds dockerhub build/push/pull steps. This should increase the transition speed between looking up drugs in different jobs.

**Comment by jjacobson95** [comment]
Closing issue. Solved by #101. End result is that it takes ~10 hours for all (~60k) drug look ups.
