### ISSUE TITLE
make data summary a table

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#102]
2 small fixes proposed for doc page:

1. Current documentation shows data summary in a really clunky format, can we just move to a table? 
![Screenshot 2024-02-26 at 7 58 44 AM](https://github.com/PNNL-CompBio/coderdata/assets/1847866/2a9cc898-1b03-4fe1-895e-62eddde9820b)

2. Also, can we use a white background or change the background on the embedded images so that they dont look like embedded images?

**Comment by jjacobson95** [comment]
Thoughts on [doc site updates](https://pnnl-compbio.github.io/coderdata/) - should the table include yes/no values for Transcriptomics, Proteomics, Mutations, and Copy Number? If you are neutral I may take them out so its a bit cleaner on a small screen. Previous method was clunky but shrunk to fit small screens nicely.
