### ISSUE TITLE
DepMap 04-drug_dosage_and_curves.py Script failing on CCLE file download

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#108]
Continuous integration failing on[ 04-drug_dosage_and_curves.py](https://github.com/PNNL-CompBio/coderdata/blob/main/build/depmap/04-drug_dosage_and_curves.py) script. This script passes "CCLE" to [04a-drugResponseData.R](https://github.com/PNNL-CompBio/coderdata/blob/main/build/depmap/04a-drugResponseData.R) which maps it to "CCLE_2015" which is passed to this command `dset<<-downloadPSet(f,saveDir='.',timeout=10000)`. This is the command which is failing.

 Error starts on this [line](https://github.com/PNNL-CompBio/coderdata/actions/runs/8199822383/job/22453086136#step:12:312). I have not been able to reproduce the issue locally. All of the other files are downloading fine within CI but this one has been consistently been failing.

Once the DepMap scripts are working (and all is aligned to updated schema), the continuous integration pipeline should be cleared!

**Comment by sgosline** [comment]
OK, I'll debug in my local build branch, hopefully over the weekend.

**Comment by jjacobson95** [comment]
Sounds great. It is now looking like it may simply be a [storage space issue](https://github.com/PNNL-CompBio/coderdata/actions/runs/8209716350/job/22465572346#step:12:310). Deleting each file after use may do it? Hopefully that makes it easier to resolve.

**Comment by jjacobson95** [comment]
Just an update, the CI pipeline is still blocked on this script.
The error message can be seen [here](https://github.com/PNNL-CompBio/coderdata/actions/runs/8330344092/job/22816123052#step:12:442). CPTAC, HCMI, BeatAML are building. MPNST will be added after this is resolved.

**Comment by sgosline** [comment]
Again, the CI will be broken for a while, focus on the poster for now, once we have a working package we can revisit the CI

**Comment by sgosline** [comment]
This works in local build - python scripts/build_locally.py --exp
