### ISSUE TITLE
DepMap Dockerfile Failing to build

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#112]
The depmap Dockerfile is now failing to build. This can be reproduced locally by running `docker build -f build/docker/Dockerfile.depmap .` from the repo base dir. Nothing has changed in the repository to cause this failure as far as I can tell. This step has been working for 2 weeks and just began to fail. 

The error can be seen [here](
https://github.com/PNNL-CompBio/coderdata/actions/runs/8239818052/job/22533892760#step:4:106) and has the following message during the apt-get install step.
```
1.101 The following packages have unmet dependencies:
1.171  libssl3t64 : Breaks: libssl3 (< 3.1.5-1.1)
1.175 E: Unable to correct problems, you have held broken packages.
```

@sgosline have you seen this before?

**Comment by sgosline** [comment]
I'm guessing something changed in one of the packages, i'll figure it out, it repros on my machine.

**Comment by jjacobson95** [comment]
Your change on local_build_script solved this issue.
