### ISSUE TITLE
Various Data fixes and Schema Alignments needed.

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#115]
This may not be up to date as I'm using some of the synapse data generated last week but I'm just trying to get ahead of a few fixes.

- BeatAML mutations file has a column titled "mutations" instead of "mutation". This should already be fixed in main, but I noticed it was wrong in those files.

- DepMap proteomics has the index column in it. just add 'index=False' argument to pd.to_csv.

- DepMap Experiments file dose_reponse_metrics have these values: fit auc', 'fit ic50', 'fit ec50', 'fit r2', 'fit ec50se', 'fit einf'. 
  - All spaces should be replaced by underscores (example: "fit auc" changed to "fit_auc"). Originally the schema had spaces in it, but this was a mistake as the spaces were invalid and causing issues.

- DepMap experiments file has these extra columns:
![Screenshot 2024-03-20 at 11 18 41 AM](https://github.com/PNNL-CompBio/coderdata/assets/85139244/79e5ccae-a889-4ce9-8644-a9d84c99d9e6)

**Comment by jjacobson95** [comment]
I'll note other issues as I find them in this thread. 

Schema alignments - all of the following must be converted from float to integer:
- improve_sample_id in depmap_experiments 
- entrez_id in depmap_proteomics
- entrez_id in depmap_transcriptomics
- entrez_id and improve_sample_id in depmap_mutations
- entrez_id in depmap_copy_number

**Comment by sgosline** [comment]
I'm guessing these were all a result of my working off of main instead of the builder branch that was way ahead, I'll get to these shortly, still fixing another docker build issue.

**Comment by jjacobson95** [comment]
Okay taking a look at the new build (2024_03_20 build) and here are a couple updates needed to get these aligned to the schema and working with the package:

- mpnst mutations file: 'mutations' column should be named 'mutation'.
- beataml mutations file: 'mutations' column should be named 'mutation'.  (This is fixed on main, just confirmed again.)
- beataml sampes file: model type has 'ex vivo' instead of 'tumor'.  (This is also fixed on main)
(also missing drugs, experiments files in this version as you mentioned you are working on)

**Comment by jjacobson95** [comment]
Another issue with the 2024_03_20 build that I just found:
Depmap proteomics file is missing most of its data. There is only proteomics info for a single sample.

**Comment by sgosline** [comment]
please create separate issues so i can tag them. this was an easy fix, and is going in the latest PR.
