### ISSUE TITLE
Add some type of slot for genes.csv file in the python package.

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#117]
Having the genes mapped (entrez id to gene name) in the DatasetLoader object would be a useful feature of this package. 

I'd also need to update the CI workflow to update FigShare with this.

**Comment by sgosline** [comment]
The gene mapping isn't being uploaded to figshare?  Are the drug mapping files being uploaded?

**Comment by jjacobson95** [comment]
The genes file and drugs file were not previously created in the CI workflow so these were never automatically pushed to Fighshare. Now that they are being created in CI, they will be pushed to Figshare, I just have to link the artifact to the upload step. But also this won't happen if there are upstream failures (and this hasn't completed successfully in a while).

Once I have the full updated data, I'll manually upload these and link the refs to the new package and documentation site. 

And I'm currently working on getting the genes file attached to the DatasetLoader object.

**Comment by sgosline** [comment]
The models cannot be build without the drugs. I'd suggest working in a function to get the drugs and drug info

**Comment by jjacobson95** [comment]
The genes file provides new information about the genes that entrez ids map to. But the individual dataset drugs files have all the same columns and info as the global drugs.tsv file. It feels redundant and likely would be confusing to users to have two drug files attached to each object.

**Comment by sgosline** [comment]
perhaps we should jsut merge to a single drug file then? is there a reason to have a dataset specfic drug file?

**Comment by jjacobson95** [comment]
Its been handled similar to the other datatypes before but it doesn't have to be. Each dataset essentially just has a subset of the global file.

I think the only real consideration is that it just adds to memory. Particularly if a user is loading in each dataset separately and each has its own full copy of the drugs info.

Even so, I am open to the idea.

**Comment by sgosline** [comment]
fixed
