### ISSUE TITLE
Update CI to use GetBeatAML.py instead of beataml_drug_retrieval.py

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#119]
[beataml_drug_retrieval.py](https://github.com/PNNL-CompBio/coderdata/pull/110/files#diff-ec0ed3c05a58477f09cf2298128c42f2dd63bbd6862504ab55fe74a2a6de9302) has been removed.

GetBeatAML.py should be updated to call pubchem_retreival.

**Comment by sgosline** [comment]
CI now runnign individual docker build commands
