### ISSUE TITLE
broad_sanger_samples.csv file not aligned to schema. 

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#124]
'source' and 'study' columns are missing.

<img width="931" alt="Screenshot 2024-03-29 at 1 23 39 PM" src="https://github.com/PNNL-CompBio/coderdata/assets/85139244/3622738e-4d4f-469f-9ed5-b5a3c0e6d490">

**Comment by sgosline** [comment]
this is a schema error, I should remove them from the YAML file.
