### ISSUE TITLE
Update doc page with current datasets

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#148]
Currently doc page does not contain MPNST data, nor does it link to latest figshare. Both of these are required for publication/release.

**Comment by sgosline** [comment]
Looks good, just trying to figure out why all the MPNST samples are tumors. will review on my end.

**Comment by jjacobson95** [comment]
Checked the mpnst files and they look good. This must be related to visualization / stats scripts - they weren't set up for Patient derived xenograft in the model type, this is probably causing the issue.

**Comment by jjacobson95** [comment]
Updated!
