### ISSUE TITLE
Ensure all datasets have the same transcriptomics normalization metric

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#154]
All transcriptomic, proteomic, etc., data should be harmonized across datasets. This should be done before we explore batch effects for the paper.

**Comment by jjacobson95** [comment]
@moonchangin I heard you you have some details on this - feel free to share in this thread.

**Comment by moonchangin** [comment]
## Issue Description

There are discrepancies in the normalization metrics used for different datasets: MPNST and BeatAML. This leads to potential issues in comparing results directly between these datasets.

### Details

- **MPNST Data**
  - Normalization Metric: TPM (Transcripts Per Million)
  - Tool: [Salmon-rnaseq workflow](https://github.com/Sage-Bionetworks/rare-disease-workflows/tree/main/rna-seq-workflow) (an alignment-free tool)

- **BeatAML Data**
  - Normalization Metric: log2(RPKM + 1)
  - Source: [Nature Article](https://www.nature.com/articles/s41586-018-0623-z)

### Proposed Solution

To harmonize the data, we propose adjusting the MPNST's TPM data to match the RPKM used in the BeatAML dataset. The adjustment can be done using the following Python code snippet, which requires the gene lengths in kilobases (kb):

```python
tpm['gene_length_kb'] = tpm['gene_length'] / 1000  # Convert gene length to kilobases
total_RNA_seq_depth = 10**6  # Placeholder for total depth in millions
tpm['rpkm'] = (tpm['transcriptomics'] * total_RNA_seq_depth) / tpm['gene_length_kb']
```

### Requirements

- **Gene Length Information**: We need to obtain the gene lengths from GENCODE version 29, which is the version used previously in the RNA-seq workflow. The gene length data should be converted from GTF format to a gene-symbol to gene-length pair in CSV format.
[gencode_v29_gene_lengths.csv](https://github.com/PNNL-CompBio/coderdata/files/15121829/gencode_v29_gene_lengths.csv)

### Code and resources used for tpm to rpkm conversion
[code_for_tpm_to_rpkm.zip](https://github.com/PNNL-CompBio/coderdata/files/15121843/code_for_tpm_to_rpkm.zip)

**Comment by sgosline** [comment]
Everything is in TPM except for BeatAML. @jjacobson95 can you please dig up the TPM for beatAML? If not, please add a conversion step.
