### ISSUE TITLE
broad_sanger samples file has quotes around all values - (breaking Polars during testing)

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#160]
Here is an attached screenshot comparing broad_sanger to cptac samples file. Quotes should be removed from all strings.

<img width="791" alt="Screenshot 2024-04-30 at 8 42 57 AM" src="https://github.com/PNNL-CompBio/coderdata/assets/85139244/fa3ef01f-bec2-4b5c-aa76-d17000051fc0">

**Comment by sgosline** [comment]
ok, can you just look to see if there are any sample identifiers with commas in them?

**Comment by jjacobson95** [comment]
Ahh I see, there are cancer_types, other_names, and common_names with commas. I'll close this and just build it into the package to check for this.

**Comment by jjacobson95** [comment]
Sorry, re-opening.   The column values are fine, but I think we should write the headers without quotes. I think any inter-dataset operations such as merge, concat, etc, won't work if the headers are different.

**Comment by sgosline** [comment]
polars has a `quote_char` argument that should handle this.
