### ISSUE TITLE
Broad_Sanger Samples File has duplicate improve_sample_ids and maybe more issues

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#164]
Duplicate improve_sample_ids can be seen in the screenshot below.  These should be unique ids.

Please note that CVCL_1588 appears at least 4 times.  Overall there are ~42,000 rows with 904 improve_sample_ids. Previously the count for unique samples in broad_sanger was 1,861.

<img width="844" alt="Screenshot 2024-05-02 at 5 12 23 PM" src="https://github.com/PNNL-CompBio/coderdata/assets/85139244/9bed8c3c-9c20-4aa0-b057-ca2c1f3cd67a">

**Comment by sgosline** [comment]
You can run a distinct/unique on the output, but i'm guessing this is because the file lists every combination of cell line name and other_name that is possible.

**Comment by sgosline** [comment]
I'm noticing from the HCMI samples that the data are limited because it wasn't properly tidied. 

Here is some more information on tidy data frames and the rationale behind them: https://r4ds.had.co.nz/tidy-data.html. Again, if there are duplicate rows then keep this open, otherwise please close.
