### ISSUE TITLE
HCMI Samples file is skipping some improve_sample_id values.

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#165]
If you look at the improve_sample_id column, you will notice it skips numbers on occasion. 

<img width="806" alt="Screenshot 2024-05-02 at 5 21 21 PM" src="https://github.com/PNNL-CompBio/coderdata/assets/85139244/89cf097d-9498-4572-8341-fb9ee38d0fb1">

**Comment by sgosline** [comment]
I'll take this since i'm rewriting the HCMI sample file.
