### ISSUE TITLE
No 00-buildGeneFile.R file in broad_sanger

### ISSUE THREAD

**Issue by coleslaw481** [PNNL-CompBio/coderdata#167]
I was trying to follow this readme: https://github.com/PNNL-CompBio/coderdata/blob/main/build/broad_sanger/README.md

and on the first step, the 2nd command:

```bash
docker run -v $PWD:/tmp/ broad_sanger Rscript 00-buildGeneFile.R
```
 expects `00-buildGeneFile.R` file, but it is not found and I get this error:
 
 ```bash
docker run -v $PWD:/tmp/ broad_sanger Rscript 00-buildGeneFile.R
Fatal error: cannot open file '00-buildGeneFile.R': No such file or directory
```

thanks,

chris

**Comment by sgosline** [comment]
Yes, this was moved to the genes docker, try using the [build script](https://github.com/PNNL-CompBio/coderdata/blob/main/build/build_all.py)
