### ISSUE TITLE
HTTPS_PROXY key error when trying to run python build/build_all.py --docker

### ISSUE THREAD

**Issue by coleslaw481** [PNNL-CompBio/coderdata#168]
Hi,

Ran into an issue following Readme.md in base of this repo.

What should I be setting HTTPS_PROXY to? Getting this error trying to build docker containers:

```bash
$ python build/build_all.py --docker
beataml
Traceback (most recent call last):
  File "build/build_all.py", line 125, in <module>
    main()
  File "build/build_all.py", line 56, in main
    res = subprocess.run(['docker','build','-t',dsname,'.','-f','build/docker/'+fn,'--build-arg','HTTPS_PROXY='+env['HTTPS_PROXY'],'--platform','linux/amd64'])
KeyError: 'HTTPS_PROXY'

```

**Comment by sgosline** [comment]
Ooh this is a good one. I assumed that it would ignore this if not found, but apparently not. I will fix.

**Comment by sgosline** [comment]
I'll have to do more documenting about how to provide access to the beataml and MPNST data. So this will have to wait, sorry.
