### ISSUE TITLE
BeatAML Drugs not generating correctly.

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#177]
Issues:
- Missing: pubchem_id, formula, weight, InChIKey, canSMILES, isoSMILES
- Incorrect: improve_drug_id
- No Drug Synonyms.
<img width="951" alt="Screenshot 2024-05-14 at 8 40 10 AM" src="https://github.com/PNNL-CompBio/coderdata/assets/85139244/4079a499-69d1-4807-94b2-37b141df68d2">

**Comment by jjacobson95** [comment]
Issue is inconsistent - I'll look more into this.

**Comment by sgosline** [comment]
i can't repro this.
