### ISSUE TITLE
Column labels as multiple rows in experiments dataframe

### ISSUE THREAD

**Issue by nkoussa** [PNNL-CompBio/coderdata#178]
It looks like the column labels got stuck inside the dataframe at some point. Not a big deal on my end, but wanted to flag it!

When I run:

dataset = coderdata.join_datasets("broad_sanger", "hcmi")
response = dataset.experiments
test = response[response.duplicated(keep=False)]
test

I get: 

Out[8]: 
          source  improve_sample_id  ...  dose_response_metric  dose_response_value
115660    source  improve_sample_id  ...  dose_response_metric  dose_response_value
3217271   source  improve_sample_id  ...  dose_response_metric  dose_response_value
3243902   source  improve_sample_id  ...  dose_response_metric  dose_response_value
3376483   source  improve_sample_id  ...  dose_response_metric  dose_response_value
5867174   source  improve_sample_id  ...  dose_response_metric  dose_response_value
6999555   source  improve_sample_id  ...  dose_response_metric  dose_response_value
35649526  source  improve_sample_id  ...  dose_response_metric  dose_response_value

[7 rows x 8 columns]

(Also - this is how I discovered this issue - the "wide" reformat option is cells by drugs but it would be nice to have one where columnA=cell, columnB=drug, columnC=source ... and then columnG=auc, columnH=ic50, ....)

**Comment by sgosline** [comment]
THis is fixed in the build, but not updated in the package yet, so i'll leave open.
