### ISSUE TITLE
build script no longer works in proper order

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#193]
With the new updated build script, if i use the `--omics` flag with the `--high_mem` flag the samples files are not built before the omics data is collected and fails.

**Comment by jjacobson95** [comment]
Mind providing more details so I can reproduce this?   

Did you also include the --samples flag? If so, how would you want me to change the behavior?

Current behavior: 
If **"--samples"** or **"--all"** arguments are received, build new samples files. 

Possible options to change it to:
A) Automatically assume that we want the samples files (and other preceding steps) are built if any later step in the pipeline is run?
B) Check for each samples file and automatically build if the file is not present.  This would be nearly impossible to determine if the samples file was complete or partial using a check like this.


**For Reproducibility, please provide the following.** 
 It is really hard to reproduce anything in this script without this information

- **Environment**:
  - If AWS, please provide AMI, Instance type, Architecture, storage amount. Or a link directly to your instance (and connect permissions).
- **Command script(s) to setup the environment**. 
  - If you don't have a command script, I need Python version, Docker version, Docker Compose Version.
- **Full Coderdata build command**
  - Example: nohup python3.10 build/build_all.py --all --pypi --figshare --version 0.1.41 > output.log 2>&1 &

**Comment by sgosline** [comment]
Ok, can you maybe provide a readme for the build_all script to describe its expected use? The command line help is a bit confusing.

**Comment by jjacobson95** [comment]
Yes, thats a good call
