### ISSUE TITLE
add doc update to build script

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#196]
Current build script will push to figshare but not update the link on the doc page. how do i get this to be included in build_all.py?

**Comment by jjacobson95** [comment]
This might be another one where we'd have to use GitHub web-hooks to trigger an action?  To update the doc page, we need to run GitHub Actions and the updated link would have to be provided somewhere online.  This could potentially be retrieved from the PyPI package.

**Comment by jjacobson95** [comment]
I thought of some other options for this - [bitly](https://bitly.com/) and [tinyurl](https://tinyurl.com/app/pricing) allow for the creation of links whose destination can be updated. However, both cost money (minimum $8-10 a month). I haven't found any free versions that could work for us.  But it did make me realize that we might be able to build a redirect service/page.

So our docs would be linked to this separate redirect page. And when users visit this page, they are immediately redirected to the latest figshare version. 

Advantage: We wouldn't have to modify our current docs page and risk any breaking changes.
Disadvantage: We would still have to modify a github page with the updated link. And there would be some time setting this up.

**Comment by sgosline** [comment]
I dont understand, cant the build_all.py script just modify the text of the docs? They're in the repo, correct?

**Comment by jjacobson95** [comment]
Yes, but there are more steps needed.

The full code would have to do the following:
- Retrieve the latest version of the Figshare link
  - Currently this is done by pushing data to figshare and extracting the link from the Figshare upload response written to figshare_latest.yaml.
- Modify the text of the docs
- Commit this change, set upstream to main (or a newly specified docs branch), and push the change back to github. 
  - We'd need to add 'GITHUB_AUTH_TOKEN' to the environment.
- Trigger a github action to rebuild the docs.

If we have a specific docs branch, we could make it so changes to the branch automatically trigger github actions to rebuild the page.



All of this can be done, I just wasn't sure if we wanted build_all.py to push updates to our GitHub repo.

**Comment by sgosline** [comment]
It sounds like the main issue is the dependency on github actions. If we remove that, we can do everything else in a script. If we decide to use github actions again, we can just have it call the script. Anyway, this is not a huge priority atm.

**Comment by jjacobson95** [comment]
This issue was resolved with the versioning code.  However there is a new related issue #216.
