### ISSUE TITLE
MPNST samples generation is failing due to a dependency issue

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#204]
Reproduced twice, same error each time.

**Error**:
```
b'Error in library(synapser) : there is no package called \xe2\x80\x98synapser\xe2\x80\x99\nExecution halted\n'
```

**Context**:
The synapser R package is not being properly downloaded into the docker image, causing the build pipeline to fail. The reason is unknown, however it looks like you may have dealt with a [dependency](https://github.com/PNNL-CompBio/coderdata/commit/42a48a4386ba3ec93ab1d46d4281224b5d5c1cf8) issue related to this recently.

**Tracing the code** we can see that the mpnst [Dockerfile](https://github.com/PNNL-CompBio/coderdata/blob/main/build/docker/Dockerfile.mpnst#L23) has an updated R base and instructions to install the [requirements.r ](https://github.com/PNNL-CompBio/coderdata/blob/main/build/mpnst/requirements.r#L3) file. The requirements.r file includes the synapser package although the 'repos' argument **differs** from the [documentation](https://r-docs.synapse.org/articles/synapser.html) which was most recently updated on 8/21/24. 

**Dockerfile build logs** confirm this is not installing correctly.
```
#106 215.4 ERROR: dependency ‘rjson’ is not available for package ‘synapser’
#106 215.4 * removing ‘/usr/local/lib/R/site-library/synapser’
#106 215.4 
#106 215.4 The downloaded source packages are in
#106 215.4      ‘/tmp/Rtmp0MtMyd/downloaded_packages’
#106 215.4 Warning message:
#106 215.4 In install.packages("synapser", repos = c("http://ran.synapse.org",  :
#106 215.4   installation of package ‘synapser’ had non-zero exit status
#106 215.4 Installing package into ‘/usr/local/lib/R/site-library’
#106 215.4 (as ‘lib’ is unspecified)
#106 215.8 also installing the dependencies ‘R.oo’, ‘R.methodsS3’
```

**To fix**, I will try updating the 'repos' argument in install.packages, and adding rjson to the requirements.r file.

**Note**: 
If we create stable docker images, we should make sure to add a test for this.

**To Reproduce**:
 - Environment:
   - AWS EC2 Instance: 
     -  Amazon Linux 2 AMI (HVM) – Kernel 5.10, SSD Volume Type
     - Architecture: 64-bit x86
     - Instance Type: t2.2xlarge
     - Storage Amount: 60Gb
     - vCPUs: 8
     - Subnet: coderdata-Public Subnet A
     - Public IP
   - Setup: 
     - I ran the two setup scripts (aws_1.sh and aws_2.sh) provided at the end of this issue, while refreshing the page between them for docker setup. I used the[ requirements.txt ](https://github.com/PNNL-CompBio/coderdata/blob/docker-build-multi/requirements.txt)file from an older version of the repo as well.  Then I set the Auth tokens.
     - Python Version 3.10.4
     - Docker Engine Version: 25.0.6
     - Docker Compose version: v2.29.2
   - Command:
     - `nohup python3.10 build/build_all.py --all --pypi --figshare --version 0.1.41 > output_2.log 2>&1 &`

**aws_1.sh**:  Setup script 1
```

# Install Git
sudo yum install git -y

# Clone the repository
git clone https://github.com/PNNL-CompBio/coderdata.git

# Install Docker and configure it
sudo amazon-linux-extras install docker -y
sudo service docker start
sudo systemctl enable docker
sudo usermod -a -G docker ec2-user

sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

echo "Part 1 completed successfully!"
```

**aws_2.sh**: Setup script 2
```
#!/bin/bash

# Display Docker info
docker info

# Install development tools
sudo yum groupinstall "Development Tools" -y

# Erase previous OpenSSL development files
sudo yum erase openssl-devel -y

# Install required libraries
sudo yum install openssl11 openssl11-devel libffi-devel bzip2-devel wget -y

# Download and install Python 3.10
wget https://www.python.org/ftp/python/3.10.4/Python-3.10.4.tgz
tar -xf Python-3.10.4.tgz
cd Python-3.10.4
./configure --enable-optimizations
make -j $(nproc)
sudo make altinstall

# Install pip for Python 3.10
sudo yum install python3-pip -y

# Change directory to coderdata and install requirements
cd ~/coderdata
pip3.10 install -r requirements.txt

# Set SYNAPSE_AUTH_TOKEN if provided
if [ -n "$1" ]; then
  export SYNAPSE_AUTH_TOKEN="$1"
  echo "SYNAPSE_AUTH_TOKEN set to $1"
else
  echo "No token provided; proceed without authentication token."
fi

echo "Part 2 completed successfully!"
```

**Comment by sgosline** [comment]
Yes, synapser failed to catch up to the numpy bug. This was finally addressed about 4 days ago, see comment on [synapser github site](https://github.com/Sage-Bionetworks/synapser/issues/334#issuecomment-2309330346).

**Comment by jjacobson95** [comment]
I don't think this was fully addressed as I ran into this current issue after the latest synapser release. I used R version 4.4.0 and Python 3.10.

**Comment by sgosline** [comment]
I think it is, since the update to the synapser docs came this week, and I haven't touched this code for over a month. Something shifted and requires updating to account for the new release.

**Comment by thomasyu888** [comment]
Hi all, just following a link here, but we also noticed the `rjson` issue, as outlined here: https://github.com/Sage-Bionetworks/synapser/blob/develop/DESCRIPTION. 

It's a bit unfortunate but since we ship for all 4 R versions, we pin the dependency of rjson to `rjson@0.2.21`.

**Comment by jjacobson95** [comment]
Thanks @thomasyu888.  I've pinned rjson to `rjson@0.2.21`, used R 4.3.2, and python3.10 and synapse now appears to be downloading correctly.  If you are interested in a stable docker container, I have one working using the following files in this commit - build/docker/Dockerfile.mpnst , build/mpnst/requirements.r, build/mpnst/requirements.txt, 61965a51fd6d40f1962ed87efa84cef804b08f63, though it has some extra files that should be removed.


However, the MPNST dataset is still not generating so I'll continue to track this here. Likely due to other dependancies or just things that have shifted in the code since the last version.

**Comment by thomasyu888** [comment]
Thanks for tagging me!  You may also want to use `reticulate@1.28` because future versions of reticulate has unintended consequences as outlined here: https://r-docs.synapse.org/articles/troubleshooting.html#using-synapser-with-reticulate
