### ISSUE TITLE
Create build_dataset.py script for building and debugging individual datasets

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#208]
When trying to build a single dataset using build_all.py, the scripts do not work as expected.

This is due to many of them being expecting file paths to previously run samples or drugs files. When the previously run ones are not included, this command fails.

Similarly, when we build datasets outside the standard order, the command fails for the same reason.

Fix: Modify scripts from each dataset to perform different actions depending on the numbers of arguments received.
- If no samples file is received, the improve_sample_id should start at 1.
- If no drugs file is received, create a new drugs file starting at SMI_1.

**Comment by sgosline** [comment]
The file dependencies is a feature, not a bug. We need every build to have the same order of building files, so we can't simply skip a dataset in a release. I'd rather stop the process if the correct file is not run.

**Comment by jjacobson95** [comment]
Okay that does make sense, however, it also makes it difficult to debug a specific dataset when we have to run the full pipeline each time.
