### ISSUE TITLE
add disjoint-set splitting to train_test_validate

### ISSUE THREAD

**Issue by ymahlich** [PNNL-CompBio/coderdata#212]
In the current state of train_test_validate disjoint-set splitting is not implemented.

Multi-label splitting is a non-trivial problem. The most straight forward approach to solving this is most likely an iterative approach, potentially something akin to [skmultilearn's iterative stratification](http://scikit.ml/api/skmultilearn.model_selection.iterative_stratification.html#module-skmultilearn.model_selection.iterative_stratification).

**Comment by sgosline** [comment]
I think we can agree to skip disjoint set at this point, and put it off to a later version, after someone request it.
