### ISSUE TITLE
Documentation update: Add which Datasets are contained within broad_sanger.

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#221]
Currently the docs don't detail exactly which cell line datasets are present within broad_sanger.

These include the following (double check that I am not missing any though):

- NCI60
- PRISM
- CCLE
- gCSI
- FIMM
- CTRPv2
- GDSCv1
- GDSCv2

**Comment by sgosline** [comment]
This is obsolete after #237
