### ISSUE TITLE
Break down broad_sanger datasets into individual datasets with no duplicates

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#227]
Currently cell line and experimental measurements are duplicated across multiple studies. Here we need to determine how to divide up each dataset into individual units with a single set of sample/drug identifiers with no duplicates. 
1- which experiments use broad vs. sanger cell lines?
2- where do proteomics measurements fall?
3- are there duplicates within studies?

**Comment by ymahlich** [comment]
With commit ce0e0c0 some helper functions have been added to the `stats` subpackage that might be helpful for this issue. We also need some of that functionality in the test/train/validate splitting, so once that branch / feature is done we might want to isolate this functionality.

The two functions in question:
https://github.com/PNNL-CompBio/coderdata/blob/ce0e0c094077ab8c8b9596985aef7ff4d79601d6/coderdata/utils/stats.py#L61
https://github.com/PNNL-CompBio/coderdata/blob/ce0e0c094077ab8c8b9596985aef7ff4d79601d6/coderdata/utils/stats.py#L19

**Comment by jjacobson95** [comment]
`split_experiments_by_study` is looking pretty darn useful here 🙂

**Proposed plan**:
1. Build combined broad_sanger dataset as we have been doing. (Making no changes to any pre-existing code).
2. Split this data into each study (found in broad_sanger_experiments.tsv) using `split_experiments_by_study`.
    - This function extracts `improve_sample_id` and `improve_drug_id` from experiments and stores them by study.
    - Then it iterates through each datatype (copy_number, transcriptomics, drugs, etc.) and sorts them by the appropriate ID to each study.
3.  For each study, write each datatype to file.
**Implementation Note**: In the build script, broad_sanger will have an additional step called "deconvolute_dataset.sh" that will be run at the end of all data builds and before validation occurs.  The validation step will be updated to check each of the new datasets separately. 

@sgosline Do you see any issues with this approach? 

___
I am essentially just doing the following and then writing to file:
___
<img width="1083" alt="Screenshot 2024-10-16 at 1 03 03 PM" src="https://github.com/user-attachments/assets/d01fc466-2f4a-42d9-9c5b-19cd542f42b3">

**Comment by sgosline** [comment]
This sounds good for the most part, but I think you have to do a second split of the omics data by study/source, depending on which cell lines to use for each experimental dataset.

**Comment by jjacobson95** [comment]
So would the final output files be something like:
- ccle_broad_proteomics.csv
- ccle_sanger_proteomics.csv
- gCSI_broad_proteomics.csv
- gCSI_sanger_proteomics.csv
- etc.


This would be split like this for each datatype within each study:
___
<img width="1134" alt="Screenshot 2024-10-16 at 1 26 22 PM" src="https://github.com/user-attachments/assets/c8679cde-75d3-4ef3-b6e1-c5ea86f4f145">

**Comment by sgosline** [comment]
that is too confusing. we should go back to the paper to see which study to use for the omics data.

**Comment by jjacobson95** [comment]
Which paper, doesn't each study have its own?

I'm still just trying to understand what the purpose of the second split would be. Or would this be a filtering step?

**Comment by sgosline** [comment]
Each study will publish the drug response data but typically allude to an omics measurement of that same cell line, but which one that is depends on the publication.

I'd rather keep both datasets, but to simplify for the cancer-agnostic user we should just stick with a single dataset.

**Comment by jjacobson95** [comment]
Okay, is there any more information you could provide?

 Or should I start looking at the CCLE, gCSI, etc. studies and filter out the omics measurements that they do not specifically say that they have?

**Comment by sgosline** [comment]
I believe you captured the original publications for the datasets - so i'd go back and read those to see which omics dataset they cite.

**Comment by sgosline** [comment]
you can filter first if you want  by selecting those with the same improve_sample_id.
