### ISSUE TITLE
Dataset description

### ISSUE THREAD

**Issue by ymahlich** [PNNL-CompBio/coderdata#228]
A general dataset overview that summarizes all datasets at once would be nice.
Maybe a "general" overview at https://pnnl-compbio.github.io/coderdata/datasets/ that then can link to a more detailed description.
I think it would be nice to see at a glance which data types are available in which dataset, especially for someone that is not yet deep in the matter and knows the datasets by heart. 
I am thinking something along the lines of a simple table akin to something like this:

| Dataset | genes | mutations | proteomics | drug_response |
|:---:|:---:|:---:|:---:|:---:|
| cptac | T | T | T | F |
| beataml | T | T | T | T |
| hcmi | T | T | F | F |

I understand that there is the functionality of coderdata_object.info() once the data is downloaded and imported but it might be nice to not have to do that prior to getting the data.

**Comment by sgosline** [comment]
will be resolved by #246
