### ISSUE TITLE
Should the schema be modified to allow "inf" values in dose_response_value?

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#234]
Should the schema be modified to allow "inf" values in dose_response_value? Or should these values be converted to null?

@sgosline I can easily add this into my branch as I am adding validation to all of the split up broad_sanger (cell line) datasets.

Getting this message in the validation script.
```
[ERROR] [/tmp/nci60_experiments.tsv/15144800] 'inf' is not of type 'number', 'null' in /dose_response_value
```

**Comment by sgosline** [comment]
set 
`range: linkml:Any`
to allow for values outside the schema.
