### ISSUE TITLE
Schema Issues Found

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#240]
Some issues have arisen now that the schema checker correctly prints all errors.  

**beataml_mutations.csv** has the additional values in its `variant_classification`.
  - missense_variant
  - frameshift_variant
  - splice_donor_variant
  - stop_gained
  - stop_lost
  - inframe_insertion
  - inframe_deletion
  
**nci60_experiments.tsv** and **gdscv1_experiments.tsv**
  - 'inf' in `dose_response_value` as noted in #234.
  - A seperate error is noted in #236.

**Comment by sgosline** [comment]
is this a naming issue in the mapping file? for example, is there another word for frameshift_variant? or is this a new type of variant that must be added to the schema?
