### ISSUE TITLE
remove drugs from CTRP dataset

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#241]
remove these drugs: 
BRD-K03911514
BRD-K07442505
BRD-K13185470
BRD-K16130065
BRD-K20514654
BRD-K27188169
BRD-K55473186
YL54
BRD-K58730230
BRD-K79669418
BRD-K99584050

**Comment by sgosline** [comment]
@jjacobson95 why dont you go ahead and add these before starting the build process.

**Comment by jjacobson95** [comment]
I will still build in code to remove them, just wondering where they are coming from.

**Comment by sgosline** [comment]
Maybe they drop out in the pubchem or structure mapping. We can just cloes this if they are not there.

**Comment by jjacobson95** [comment]
It could be that they were missing due to the incompleteness of the previous build.  I already added it to the pipeline in the drop_drugs branch so it shouldn't hurt to have.

**Comment by sgosline** [comment]
So can we close this?

**Comment by jjacobson95** [comment]
Once we merge PR #252, this will close.
