### ISSUE TITLE
Why do we create new drug IDs (improve_drug_id)? 

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#248]
(***Feel free to close once answered***)

With every drug, we have a matching PubChem identifier, why do we have both IDs when one of them is publicly available and searchable already?  Is this just an artifact from the IMPROVE project specifications?

**Drug File:**
<img width="986" alt="Screenshot 2024-11-13 at 2 02 58 PM" src="https://github.com/user-attachments/assets/b90340dc-f810-49c3-941d-ce7928f70576">

**Experiments File:**
<img width="826" alt="Screenshot 2024-11-13 at 2 03 57 PM" src="https://github.com/user-attachments/assets/c33fb093-bce3-401b-b2a8-d375ee37f32b">
*Experiments are linked to improve_sample_ids but this could easily be swapped to pubchem ID.*

**Comment by sgosline** [comment]
I'm not sure what you mean by 'both ids'. We keep the pubchem ID and name so we dont have to pull data twice. For every dataset, we can search the drug data first (by name, pubchem id) and only if we come up empty do we have to poll pubchem.

**Comment by sgosline** [comment]
Pubchem Ids are NOT unique - there are many for a single structure.

**Comment by jjacobson95** [comment]
I meant for improve_drug_id and pubchem_id

**Comment by jjacobson95** [comment]
Does each SMILES string correspond to just one pubchem_id?

**Comment by sgosline** [comment]
No.

**Comment by jjacobson95** [comment]
Okay thanks, that was the source of my confusion.

**Comment by jjacobson95** [comment]
Also this is my current understanding - feel free to correct:

A SMILES string may correspond to multiple structures.
An ISOSMILES string may correspond to multiple but fewer structures than SMILES.
An InChIKey corresponds to a single structure.

A single pubchem ID may map to multiple SMILES or ISOSMILES strings.
A single pubchem ID will only map to a single InChIKey

**Comment by sgosline** [comment]
I think all claims above are correct except for the single pubchemID -to-InChIKey mapping, i'm pretty sure these are also many to one.
