### ISSUE TITLE
GDC Client Changed URL and file format in Latest update

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#254]
This breaks HCMI which uses the GDC data transfer tool.  A fix is in progress.

Their URL was updated.
Their File structure within the downloaded zip file was also changed.

**Comment by sgosline** [comment]
I fixed this in the PDO branch: https://github.com/PNNL-CompBio/coderdata/blob/panc_pdo/build/hcmi/02-getHCMIData.py

**Comment by jjacobson95** [comment]
Great, I've also got this fixed on drop_drugs.
