### ISSUE TITLE
ids stored as floats in beataml_transcriptomics

### ISSUE THREAD

**Issue by ymahlich** [PNNL-CompBio/coderdata#255]
`improve_sample_id` & `entrez_id` are stored as `float` in `beataml_transcriptomics.csv.gz` (see example below). This is inconsistent with the `entrez_id` in the `genes` table as well as `improve_sample_id` in the `experiments` table for example (both are integers).

This behavior is present for the dataset v0.1.4 on figshare (https://figshare.com/articles/dataset/CODERData0_1_4/26409316) / v0.1.40 on pypi (https://pypi.org/project/coderdata/)

I did not check other files besides beataml_transcriptomics, beataml_experiments & genes.

Sample lines from `beataml_transcriptomics.csv.gz`:
```
improve_sample_id,transcriptomics,entrez_id,source,study
3334.0,0.4719481112214393,7105.0,synapse,BeatAML
3334.0,0.0,64102.0,synapse,BeatAML
```

**Comment by jjacobson95** [comment]
Full list of files to be updated from the latest versions. MPNST will have to be double checked as this is getting updates.

- broad_sanger_experiments (all split files):  improve_sample_id
- beataml_transcriptomics: improve_sample_id, entrez_id
- beataml_proteomics: entrez_id
- cptac_transcriptomics: entrez_id
- cptac_proteomics: entrez_id
- cptac_mutations: entrez_id
- cptac_copy_number: entrez_id
