### ISSUE TITLE
Create script that pulls data model from figshare

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#27]
Given that we are storing the data schemas on figshare, we need a function in python that downloads the data and loads the relevant tables into data frames. 

For example, the cell line data is here:https://figshare.com/s/525f7777039f4610ef47

https://knowledge.figshare.com/apps is the list of integrations with figshare.

**Comment by sgosline** [comment]
This was partially addressed by #30 but needs work. @sydneysc  can you please hard code in the different URLs for the data types and add in two flags, one for `--dataType` that allows for download of transcriptomics, proteomics, cnv, mutation, or sample data and `--modelType` that allows for cptac, cellLine, beatAML and hcmi data?

**Comment by sgosline** [comment]
this has been done and is in the scripts directory

**Comment by jjacobson95** [comment]
This is being built into the package.  Still in progress. 

To do:
Automate updating the figshare pull links with each version.
- This can be done in a similar method to how the docs will be updated.

**Comment by jjacobson95** [comment]
Closing. This has been integrated into the python package portion of this application.
