### ISSUE TITLE
Come up with package/dataset name

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#41]
We should rename the repo to account for new name. Ideas?

**Comment by jjacobson95** [comment]
Just putting up some suggestions from our future ruler (GPT) that may inspire some ideas. 
I like TumorTensors.

TumorTensors   
Description: A play on "tensor", a core data structure in deep learning, and tumors.

OncoPyPacks
Description: A collection/package of oncology datasets for Python.

DeepCancerSets
Description: Highlighting its utility for deep learning on cancer datasets.

OncoIngest
Description: Indicating it's for oncology data and geared towards data ingestion for models.

CancerFeeder
Description: The idea being that the package "feeds" cancer data to deep learning models.

Cancer2Tensor
Description: Conveying the transformation of cancer datasets into tensor format for deep learning.

OncoDeepDive
Description: Suggesting a deep dive into oncology data for deep learning.

**Comment by sgosline** [comment]
More ideas: 
- DROCan - dose response and omics in cancer
- DrugOmics  - boring
- MiCanDO - models in cancer drugs and omics.

**Comment by jjacobson95** [comment]
Maybe MiCanDO?  Although could this be confusing because we aren't providing the models to run on cancer data?

We could also use Rx instead of drug in the name, I haven't been able to think of any good non-taken names though.

TROM is nice and simple. Easy to say and remember.

**Comment by sgosline** [comment]
I think Cancer Omics Drug Response Dataset (codr-data) is the package name? I dont remember what python package names should be like, other than the lowercase thing. are they allowed to have a dahs? should we rename the repo?

**Comment by jjacobson95** [comment]
Seems like a general consensus that dashes should not be used. Underscores are also [discouraged](https://peps.python.org/pep-0008/#package-and-module-names) but are better. And no camelcase either. So no perfect option, but I think codrdata would adhere best to the guidelines. 
codr_data: allowable but not recommended based on readings. This is the most clear though.
codrdata: acceptable but least clear. 
codr: acceptable and clear but missing info

**Comment by sgosline** [comment]
I can't stand underscores, I'm not sure why. I'm sure they're nice punctuation.  What do you think? Should we call it the the multiple d's in codrdata or even codrd is difficult to type/read. Maybe codr is best - what do you think?

**Comment by jjacobson95** [comment]
I like codr best, but looks like this name is taken by this abandoned [package](https://pypi.org/project/codr/) in python and this semi-abandoned [one](https://snyk.io/advisor/npm-package/codr) in JS.

Maybe codrdata is best. Unless we could find a good E word for coderdata? 
Cancer Omics Drug Evaluation Response Dataset ?
