### ISSUE TITLE
new dataset request: Add drug perturbation data from CMAP 

### ISSUE THREAD

**Issue by BelindaBGarana** [PNNL-CompBio/coderdata#47]
It would be great if the following data set could be added to IMPROVE:

- Cmap drug perturbation data (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE101406 from https://www.sciencedirect.com/science/article/pii/S2405471218301091?via%3Dihub and https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5990023/)

Thanks in advance!

**Comment by sgosline** [comment]
@BelindaBGarana  can you maybe provide a desired format for the data? Currently we have the input data, a drug file, and an 'experiments' table that maps the dose response. What would the 'experiments' file data be in your approach?

**Comment by sgosline** [comment]
I'm not sure what "perturbation" data is, but do we need separate files, or can we append into a single file with distinct 'source' and 'study' columns differentiating between the acronyms (akin to our current experiments.csv file)

**Comment by sgosline** [comment]
Proposed schema (perturbations.csv):
entrez_id
improve_sample_id
gene_measurement
data_type [transcriptomics]
perturbation: [improve_drug_id]
perturbation_type: [drug, gene]
