### ISSUE TITLE
new dataset request: Add in PDX omics data and microtissue dose response

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#48]
We need to  add in the following datasets:
1- summarized somatic mutations of PDX
2- copy number of PDX
3- RNASeq of PDX
4- dose response of drugs in MT
5- tumor growth response in PDX (need new data model for this)

**Comment by sgosline** [comment]
http://synapse.org/mxm is the data for the the PDX and MT.

**Comment by moonchangin** [comment]
[Merge pull request](https://github.com/PNNL-CompBio/coderdata/commit/599294f04344b964dae6547c4aac2a00d8c3036c) https://github.com/PNNL-CompBio/coderdata/pull/73 [from PNNL-CompBio/get_mpnst](https://github.com/PNNL-CompBio/coderdata/commit/599294f04344b964dae6547c4aac2a00d8c3036c)

Will now work on a new branch for processing drug data

**Comment by sgosline** [comment]
MPNST data is added, creaeting new ISsue for PDX
