### ISSUE TITLE
Create a strategy for updating builds with new data versions

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#55]
Scenario 1: something like CPTAC updates on the backend, so when we re-run it will pull new data
Scenario 2: we change the scripts to pull from a new data repository

how do we increment the version for this?

**Comment by jjacobson95** [comment]
We should discuss the following nuances:
- Importing data versions from each dataset. I don't think that each is maintained in an easy way to do this, so we might have to create our own versioning system.
- Github code version.  This should be linked to PyPI and Figshare. So if github is at version 0.1.41, so should PyPI and Figshare.
  - I think each of these should be their own "Github Release" and tagged to match the version number. This could also allow us other commits in between tags.
  - [Release version](https://github.com/PNNL-CompBio/coderdata/releases/tag/v0.1.0)
  
It seems like there are two possible implementations here:
 - For each **Release**, we could setup a github action to start an AWS EC2 instance, set up environment, run dataset generation.
    - Issues: 
      - I don't know how hard it would be to do this with a PNNL AWS account. 
      - Error handling would be difficult to say the least.
- For each **Manual AWS EC2 Run**, we may be able to setup webhooks to see when PyPI or Figshare is updated, grab the version number, and update github with it
  - Issues:
   - Less automated.  
   - Not sure where we would store the dataset versioning info.
 - Alternate option: maybe have our script trigger AWS lambda webhook upon successful completion https://aws.amazon.com/blogs/compute/dynamic-github-actions-with-aws-lambda/

**Comment by jjacobson95** [comment]
This issue is resolved.

Every time we run the build_all.py script and with the required arguments, this will automatically build all data, upload to all locations, and version the github repository.

Required Arguments: --pypi --figshare --version [#.#.#] --github-username  [username] --github-email [email]
