### ISSUE TITLE
Continuous Integration Via Github Actions (Overview)

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#57]
Full list of steps needed for CI.
- [x] Build/Push DepMap to Dockerhub
- [x] Build/Push CPTAC to Dockerhub
- [x] Build/Push HCMI to Dockerhub
- [x] Build/Push BeatAML to Dockerhub
- [ ] Build/Push MPNST to Dockerhub
- [x] Build DepMap Samples File.  
- [x] Build CPTAC Samples File. 
- [x] Build HCMI Samples File. 
- [x] Build BeatAML Samples File. 
- [ ] Build MPNST Samples File. 
- [x] Build BeatAML Drug Data
- [x] Build DepMap Drug Data
- [ ] Check Drug Schema
- [x] Build HCMI Data 
- [x] Build BeatAML Data 
- [ ] Build DepMap Data
- [x] Build CPTAC Data 
- [ ] Build MPNST Data 
- [x] HCMI - check schema 
- [x] BeatAML - check schema 
- [ ] DepMap - check schema 
- [x] CPTAC - check schema 
- [ ] MPNST - check schema 
- [x] Upload Data to Figshare
- [x] Data Visualization / Stats
- [x] Update stats file with Visualization info and Figshare link.
- [x] Update Docs with Data Visualization and Figshare Link
- [x] Unit Test: Download (bash)
- [x] Unit Test: Download (python)
- [x] Unit Test: Load (python)
- [x] Unit Test: Reformat (python)
- [x] Unit Test: Join (python)
- [x] Unit Test: Info (python)
- [x] Push updated version of package to PyPI.

**Build** Steps:  
- Create Dockerfile / Build Docker image
- [Workflow](https://github.com/PNNL-CompBio/coderdata/blob/main/.github/workflows/main.yml) update
- For samples file generation, create samples file. Save as artifact, pass to next samples file generator.

**Update** Steps:
- Checkout Action to get local repo files.
- Modify File via a python script.
- Push to Github. 

**Data Visualization** Steps:
- Pull newly generated files via artifacts
- Generate Stats
- Generate Visualization PNGs
- Return all as artifacts. These will then be used in next steps.

Notes:
- Build steps will be sequential unless we decide to generate each samples file first.
- A stats file should be created. Maybe Yaml or Json. This will include info on stats and the Figshare link. This information will be parsed and docs will be updated with that info.

**Comment by jjacobson95** [comment]
A couple notes - I am checking off boxes that are completed in their own branches.
BeatAML/HCMI build steps and FigShare upload are in builder_branch_JJ.
Unit tests and PyPi upload is in package_dev_JJ.

To do:
Data visualization and the docs updates will be in the  builder_branch_JJ.

**Comment by sgosline** [comment]
I'm working on the build scripts for cptac and cell_line data.

**Comment by jjacobson95** [comment]
Edited tasks above to include steps for dockerhub, drugs, schema.

**Comment by jjacobson95** [comment]
This is out of date. We are no longer using github actions to build all of our data with each commit.  

Closing
