### ISSUE TITLE
METRICS: measure how many drugs per sample, and how many samples per drug

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#6]
create script that loads experiments and samples and determines how many samples we have per drug, and how many drugs per sample. Generate table with with results and appropriate plots.

**Comment by jjacobson95** [comment]
Closing issue.
Stats are generated in this [script](https://github.com/PNNL-CompBio/coderdata/blob/main/scripts/gen_stats.py) and automatically updated in docs (when CI is working). Visualization is done in these two scripts ([vis1](https://github.com/PNNL-CompBio/coderdata/blob/main/dataSummary/visualization01.R) and [vis2](https://github.com/PNNL-CompBio/coderdata/blob/main/dataSummary/visualization02.R)) which also automatically updated in docs.
