### ISSUE TITLE
CPTAC "mutation " data prefix doesn't fit schema and tests. (it should be "mutations")

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#68]
Update dtype in "mutation" to "mutations" in this [line](https://github.com/PNNL-CompBio/coderdata/blob/main/build/cptac/getCptacData.py#L262C78-L262C78x). Not sure of other possible affects on code otherwise I'd do it myself.

```
for dtype in ['mutation','proteomics','transcriptomics','copy_number']: #'miRNA doesnt work
```

**Comment by sgosline** [comment]
I think this was fixed in #72
