### ISSUE TITLE
Documentation Overview

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#70]
- [x] Create Base page
- [x] Format Header
- [x] Dynamically update Header links for each Figshare version
- [ ] Finalize Logo
- [x] Complete Main page
- [x] Complete HCMI page
- [x] Complete BeatAML page
- [x] Complete CPTAC page
- [x] Complete Cell Line page
- [x] Complete Usage page with all info on functions and nuances
- [x] Complete Contribution page 
- [x] Complete Secondary Contribution page with info on code/data additions from users.
- [x] Create all links between pages
- [x] Dynamically update Visualization on all pages
- [x] Dynamically update tables on all four dataset pages
- [x] Dynamically update stats
- [ ] Finalize styling

Each dataset page needs:
Two plots, Table, Description

**Comment by sgosline** [comment]
Can we add in 'example code' for each function? I'd like
1- examples of omics data (download, calculate a gene or two expression across different datasets (maybe same cell line)
2- example of drug data (download, plot drug AUCs across same cell line, different datasets)

**Comment by jjacobson95** [comment]
This one fell off the radar for me, I'll work on it when I get a chance though. Could you clarify on the calculating gene expression example - is this imputation example?

And I will also include a deep learning model example using the keras functional API in python.
