### ISSUE TITLE
Package Development Overview

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#71]
- [x] Create PyPI Repo
- [x] Format Directory to function as a Python Package
- [x] Set version and Increment with each push.
- [x] Create Download Function for CLI
- [x] Create Download Function for Python
- [x] Create Load Function for Python
- [x] Create Reformat Long to Wide Function for Python
- [x] Create Reformat Wide to Long Function for Python
- [x] Create Reload Function for Python
- [x] Create Join Function for Python
- [x] Create Information Function for Python
- [x] Create Tests for each and add to CI
- [x] Automatically Push to PyPI with each push
- [x] Integrate everything into the larger Continuous Integration Pipeline

**Comment by jjacobson95** [comment]
Package Development is done for now. I'll leave this open a little while longer in case we think of additional functions to include. Visualization?

**Comment by sgosline** [comment]
I dont think visualization is as important as documentation for now - visualization can come from the examples we provide.
