### ISSUE TITLE
CPTAC Columns not named correctly.

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#77]
mutations file - "mutation" column should be "mutations".
copy_number file - "CNV" should be "copy_number".

This is causing some issues with the join_datasets function I'm working on. It will also cause issues with the schema.

**Comment by sgosline** [comment]
How do I repro this? It's working on my end.

**Comment by jjacobson95** [comment]
Sorry, I'll mark as resolved. Looks like the code is updated, but the files aren't yet.  This should resolve itself once CPTAC is integrated into the CI.
