### ISSUE TITLE
Cell Line Sample File Generation Error

### ISSUE THREAD

**Issue by jjacobson95** [PNNL-CompBio/coderdata#81]
See error here:
https://github.com/PNNL-CompBio/coderdata/actions/runs/7659884305/job/20876973758#step:6:125

**Comment by sgosline** [comment]
I can't reproduce that error.

**Comment by jjacobson95** [comment]
Odd it just came up with no related changes to the repo. 

Is this ftp usually inaccessible from the browser?
https://ftp.expasy.org/databases/

**Comment by sgosline** [comment]
I bet it’s the same site that hosts biomart , and James Moon was saying that biomaet was down

Sent from my iPhone

On Jan 25, 2024, at 2:43 PM, Jeremy Jacobson ***@***.***> wrote:

﻿
Check twice before you click! This email originated from outside PNNL.


Odd it just came up with no related changes to the repo.

Is this ftp usually inaccessible from the browser?
https://ftp.expasy.org/databases/
