### ISSUE TITLE
Consider building static versioned docker images

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#88]
Currently our continuous integration has each docker image being built on the fly, which makes it challenging to ensure that the data and packages being used are stable. We can instead build each docker image and store it on docker hub, then just pull from docker hub to build data package.

**Comment by jjacobson95** [comment]
Not a bad idea, this should make our pipeline for stable. Do you know if any of the packages we use to pull data are linked to specific versions of data? For example, is an older version of the cptac package linked to an older version of their data?

**Comment by sgosline** [comment]
The package seems to pull from zenodo. But it [breaks frequently](https://github.com/PayneLab/cptac/issues?q=+is%3Aissue+author%3Asgosline+).

**Comment by jjacobson95** [comment]
This would speed up the CI quite a bit - particularly the drug generation portion.

**Comment by jjacobson95** [comment]
I'll do this. Should these be linked to a specific account or should I use my own?

**Comment by jjacobson95** [comment]
Not versioned, but DockerHub build/push/pull added to CI for efficiency reasons. This will be in PR #101.

**Comment by jjacobson95** [comment]
Docker images are now built at the beginning of the CI pipeline. These can be a separate workflow once they no longer need to be updated so frequently.

**Comment by sgosline** [comment]
Created new build.yml file to just build docker files, now just need to figure out how to version.

**Comment by jjacobson95** [comment]
This is automatically versioned now whenever build_all.py pushes to main. Resolved.
