### ISSUE TITLE
Move chemical structure lookup to python

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#99]
current version of mapDrugsToPubchem.R requires the addition of rdkit and mordred functionality. This is an issue to:
1- move the script to python
2- update the cell line drug data to call it directly instead of calling the R script (via reticulate)
3- update drug schema to allow for chemical descriptors
4- update the script to add chemical descriptors

**Comment by jjacobson95** [comment]
Bullets 1 and 2 are done. Which chemical descriptors should we add to this?

**Comment by sgosline** [comment]
RDKit and mordred, but hold off on this until the MPNST data is added tot he main build, since the abstract is due on Friday.

**Comment by sgosline** [comment]
this is done.
